//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_Resume_WebApplication
{


    public partial class Website
    {

        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl appSidebar;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder NavigationContent;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl mainWrap;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl appTopbar;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl contentInner;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder FooterContent;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder PageScripts;
    }
}
